object Versions {
    const val kotlin = "1.6.0"
    const val kotlinCore = "1.7.0"
    const val kotlinCoroutines = "1.4.1"
    const val androidxAppCompat = "1.2.0"
    const val androidxMaterial = "1.2.0"
    const val activityKtx = "1.4.0"
    const val fragmentKtx = "1.4.1"
    const val constraintLayout = "2.1.2"
    const val navComponents = "2.3.5"
    const val permissionDispatcher = "4.8.0"
    const val timber = "4.7.1"
    const val androidYoutubePlayer = "10.0.3"
    const val glide = "4.8.0"
    const val squareOkHttp = "4.9.1"
    const val retrofit = "2.9.0"
    const val materialDialogs = "3.3.0"
    const val hilt = "2.40.5"
    const val junit4 = "4.13.2"
    const val junitExt = "1.1.2"
    const val espressoCore = "3.4.0"
}